--------------------------------------------------------
--  File created - niedziela-stycznia-27-2019
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table KIEROWCY
--------------------------------------------------------

  CREATE TABLE "ADMIN"."KIEROWCY"
   (	"ID" NUMBER(*,0),
	"ID_OSOBY" NUMBER,
	"ID_SAMOCHODU" NUMBER,
	"PENSJA" NUMBER(*,0),
	"WIEK" NUMBER(*,0),
	"PRACUJE" VARCHAR2(20 BYTE)
   ) SEGMENT CREATION IMMEDIATE
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table KLIENCI
--------------------------------------------------------

  CREATE TABLE "ADMIN"."KLIENCI"
   (	"ID" NUMBER,
	"ID_OSOBY" NUMBER,
	"EMAIL" VARCHAR2(20 BYTE),
	"HASLO" VARCHAR2(20 BYTE)
   ) SEGMENT CREATION IMMEDIATE
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table OSOBY
--------------------------------------------------------

  CREATE TABLE "ADMIN"."OSOBY"
   (	"ID" NUMBER(*,0),
	"IMIE" VARCHAR2(20 BYTE),
	"NAZWISKO" VARCHAR2(20 BYTE),
	"MIASTO" VARCHAR2(20 BYTE),
	"ULICA" VARCHAR2(20 BYTE),
	"NRDOMU" NUMBER(*,0),
	"NRMIESZKANIA" NUMBER(*,0),
	"OSTRZEZENIA" NUMBER(*,0),
	"KONTO" NUMBER(16,0)
   ) SEGMENT CREATION IMMEDIATE
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table PRZEJAZDY
--------------------------------------------------------

  CREATE TABLE "ADMIN"."PRZEJAZDY"
   (	"ID" NUMBER(*,0),
	"ODBIOR" VARCHAR2(20 BYTE),
	"CEL" VARCHAR2(20 BYTE)
   ) SEGMENT CREATION IMMEDIATE
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table REZERWACJE
--------------------------------------------------------

  CREATE TABLE "ADMIN"."REZERWACJE"
   (	"ID" NUMBER(10,0),
	"ID_KIEROWCY" NUMBER(*,0),
	"ID_KLIENTA" NUMBER(*,0),
	"CENA" NUMBER(*,0),
	"ID_ZAMOWIENIA" NUMBER,
	"ID_PRZEJAZDU" NUMBER,
	"DATA_ROZPOCZECIA" DATE,
	"DATA_ZAKONCZENIA" DATE,
	"CZAS_ZAKOCZENIA" VARCHAR2(40 BYTE),
	"CZAS_ROZPOCZECIA" VARCHAR2(40 BYTE)
   ) SEGMENT CREATION IMMEDIATE
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table SAMOCHODY
--------------------------------------------------------

  CREATE TABLE "ADMIN"."SAMOCHODY"
   (	"ID" NUMBER(*,0),
	"MARKA" VARCHAR2(20 BYTE),
	"ROK_PRODUKCJI" NUMBER(*,0),
	"STAN" VARCHAR2(20 BYTE),
	"MODEL" VARCHAR2(20 BYTE)
   ) SEGMENT CREATION IMMEDIATE
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table ZAMOWIENIA
--------------------------------------------------------

  CREATE TABLE "ADMIN"."ZAMOWIENIA"
   (	"ID" NUMBER(*,0),
	"ODBIOR" VARCHAR2(20 BYTE),
	"CEL" VARCHAR2(20 BYTE)
   ) SEGMENT CREATION IMMEDIATE
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Sequence KIEROWCY_SEQ1
--------------------------------------------------------

   CREATE SEQUENCE  "ADMIN"."KIEROWCY_SEQ1"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 21 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE  GLOBAL ;
--------------------------------------------------------
--  DDL for Sequence KLIENCI_SEQ1
--------------------------------------------------------

   CREATE SEQUENCE  "ADMIN"."KLIENCI_SEQ1"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 27 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE  GLOBAL ;
--------------------------------------------------------
--  DDL for Sequence OSOBY_SEQ
--------------------------------------------------------

   CREATE SEQUENCE  "ADMIN"."OSOBY_SEQ"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 27 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE  GLOBAL ;
--------------------------------------------------------
--  DDL for Sequence PRZEJAZDY_SEQ
--------------------------------------------------------

   CREATE SEQUENCE  "ADMIN"."PRZEJAZDY_SEQ"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 121 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE  GLOBAL ;
--------------------------------------------------------
--  DDL for Sequence REZERWACJE_SEQ1
--------------------------------------------------------

   CREATE SEQUENCE  "ADMIN"."REZERWACJE_SEQ1"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 41 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE  GLOBAL ;
--------------------------------------------------------
--  DDL for Sequence SAMOCHODY_SEQ1
--------------------------------------------------------

   CREATE SEQUENCE  "ADMIN"."SAMOCHODY_SEQ1"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 21 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE  GLOBAL ;
--------------------------------------------------------
--  DDL for Sequence ZAMOWIENIA_SEQ
--------------------------------------------------------

   CREATE SEQUENCE  "ADMIN"."ZAMOWIENIA_SEQ"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 21 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE  GLOBAL ;
REM INSERTING into ADMIN.KIEROWCY
SET DEFINE OFF;
Insert into ADMIN.KIEROWCY (ID,ID_OSOBY,ID_SAMOCHODU,PENSJA,WIEK,PRACUJE) values ('1','5','1','2100','23','NIE');
Insert into ADMIN.KIEROWCY (ID,ID_OSOBY,ID_SAMOCHODU,PENSJA,WIEK,PRACUJE) values ('2','6','2','2300','25','NIE');
Insert into ADMIN.KIEROWCY (ID,ID_OSOBY,ID_SAMOCHODU,PENSJA,WIEK,PRACUJE) values ('3','7','3','24500','25','TAK');
REM INSERTING into ADMIN.KLIENCI
SET DEFINE OFF;
Insert into ADMIN.KLIENCI (ID,ID_OSOBY,EMAIL,HASLO) values ('23','17','WER','WER');
Insert into ADMIN.KLIENCI (ID,ID_OSOBY,EMAIL,HASLO) values ('24','18','adamiak@wp.pl','xyz');
Insert into ADMIN.KLIENCI (ID,ID_OSOBY,EMAIL,HASLO) values ('6','20','xcv','xcv');
Insert into ADMIN.KLIENCI (ID,ID_OSOBY,EMAIL,HASLO) values ('7','21','vbn','vbn');
Insert into ADMIN.KLIENCI (ID,ID_OSOBY,EMAIL,HASLO) values ('1','1','email@wp.pl','haslo');
Insert into ADMIN.KLIENCI (ID,ID_OSOBY,EMAIL,HASLO) values ('2','2','poczta@gmail.com','dobreHaslo');
Insert into ADMIN.KLIENCI (ID,ID_OSOBY,EMAIL,HASLO) values ('3','3','mojapoczta@gmail.com','xyz');
Insert into ADMIN.KLIENCI (ID,ID_OSOBY,EMAIL,HASLO) values ('4','4','qwerty@gmail.com','xyz');
REM INSERTING into ADMIN.OSOBY
SET DEFINE OFF;
Insert into ADMIN.OSOBY (ID,IMIE,NAZWISKO,MIASTO,ULICA,NRDOMU,NRMIESZKANIA,OSTRZEZENIA,KONTO) values ('8','TEST','TEST','TEST','TEST','12','12','0','12');
Insert into ADMIN.OSOBY (ID,IMIE,NAZWISKO,MIASTO,ULICA,NRDOMU,NRMIESZKANIA,OSTRZEZENIA,KONTO) values ('9','asd','asd','ads','asd','12','12','0','12');
Insert into ADMIN.OSOBY (ID,IMIE,NAZWISKO,MIASTO,ULICA,NRDOMU,NRMIESZKANIA,OSTRZEZENIA,KONTO) values ('10','zxc','zxc','zxc','zxc','12','12','0','12');
Insert into ADMIN.OSOBY (ID,IMIE,NAZWISKO,MIASTO,ULICA,NRDOMU,NRMIESZKANIA,OSTRZEZENIA,KONTO) values ('11','bnm','bnm','bnm','bnm','14','14','0','14');
Insert into ADMIN.OSOBY (ID,IMIE,NAZWISKO,MIASTO,ULICA,NRDOMU,NRMIESZKANIA,OSTRZEZENIA,KONTO) values ('12','iop','iop','iop','iop','12','12','0','12');
Insert into ADMIN.OSOBY (ID,IMIE,NAZWISKO,MIASTO,ULICA,NRDOMU,NRMIESZKANIA,OSTRZEZENIA,KONTO) values ('13','cvb','cvb','cvb','cvb','12','12','0','12');
Insert into ADMIN.OSOBY (ID,IMIE,NAZWISKO,MIASTO,ULICA,NRDOMU,NRMIESZKANIA,OSTRZEZENIA,KONTO) values ('14','xcv','xcv','xcv','xcv','234','234','0','234');
Insert into ADMIN.OSOBY (ID,IMIE,NAZWISKO,MIASTO,ULICA,NRDOMU,NRMIESZKANIA,OSTRZEZENIA,KONTO) values ('15','tyu','tyu','tyu','tyu','5675','567','0','567');
Insert into ADMIN.OSOBY (ID,IMIE,NAZWISKO,MIASTO,ULICA,NRDOMU,NRMIESZKANIA,OSTRZEZENIA,KONTO) values ('16','hjk','hjk','hjk','hjk','567','567','0','567');
Insert into ADMIN.OSOBY (ID,IMIE,NAZWISKO,MIASTO,ULICA,NRDOMU,NRMIESZKANIA,OSTRZEZENIA,KONTO) values ('17','WER','WER','WER','WER','312','123','0','123');
Insert into ADMIN.OSOBY (ID,IMIE,NAZWISKO,MIASTO,ULICA,NRDOMU,NRMIESZKANIA,OSTRZEZENIA,KONTO) values ('18','Grzegorz','Adamiak','kielce','warszawska','27','12','0','123123123123123');
Insert into ADMIN.OSOBY (ID,IMIE,NAZWISKO,MIASTO,ULICA,NRDOMU,NRMIESZKANIA,OSTRZEZENIA,KONTO) values ('19','xcv','xcv','xcv','xcv','12','12','0','21');
Insert into ADMIN.OSOBY (ID,IMIE,NAZWISKO,MIASTO,ULICA,NRDOMU,NRMIESZKANIA,OSTRZEZENIA,KONTO) values ('20','xcv','xvc','xvc','xcv','324','234','0','24');
Insert into ADMIN.OSOBY (ID,IMIE,NAZWISKO,MIASTO,ULICA,NRDOMU,NRMIESZKANIA,OSTRZEZENIA,KONTO) values ('21','nbvn','vnb','vbn','vbn','123','123','0','123');
Insert into ADMIN.OSOBY (ID,IMIE,NAZWISKO,MIASTO,ULICA,NRDOMU,NRMIESZKANIA,OSTRZEZENIA,KONTO) values ('1','ADAM','KOWALSKI','KIELCE','KRAKOWSKA','12','5','0',null);
Insert into ADMIN.OSOBY (ID,IMIE,NAZWISKO,MIASTO,ULICA,NRDOMU,NRMIESZKANIA,OSTRZEZENIA,KONTO) values ('2','PIOTR','KOWALSKI','KIELCE','WARSZAWSKA','7','5','0',null);
Insert into ADMIN.OSOBY (ID,IMIE,NAZWISKO,MIASTO,ULICA,NRDOMU,NRMIESZKANIA,OSTRZEZENIA,KONTO) values ('3','PIOTR','NOWAKOWSKI','KIELCE','1 MAJA','1','10','0',null);
Insert into ADMIN.OSOBY (ID,IMIE,NAZWISKO,MIASTO,ULICA,NRDOMU,NRMIESZKANIA,OSTRZEZENIA,KONTO) values ('4','DAREK','FRANKIEWICZ','KIELCE','GORNA','11','10','0',null);
Insert into ADMIN.OSOBY (ID,IMIE,NAZWISKO,MIASTO,ULICA,NRDOMU,NRMIESZKANIA,OSTRZEZENIA,KONTO) values ('5','LUKASZ','NOWAK','KIELCE','ALEJA SOLIDARNOSCI','12','5','0',null);
Insert into ADMIN.OSOBY (ID,IMIE,NAZWISKO,MIASTO,ULICA,NRDOMU,NRMIESZKANIA,OSTRZEZENIA,KONTO) values ('6','MONIKA','NOWAK','KIELCE','ALEJA SOLIDARNOSCI','12','5','0',null);
Insert into ADMIN.OSOBY (ID,IMIE,NAZWISKO,MIASTO,ULICA,NRDOMU,NRMIESZKANIA,OSTRZEZENIA,KONTO) values ('7','KATARZYNA','WESOLOWSKA','KIELCE','SWIETOKRZYSKA','42','5','0',null);
REM INSERTING into ADMIN.PRZEJAZDY
SET DEFINE OFF;
Insert into ADMIN.PRZEJAZDY (ID,ODBIOR,CEL) values ('21','kielce','krakow');
Insert into ADMIN.PRZEJAZDY (ID,ODBIOR,CEL) values ('22','kielce','staszów');
Insert into ADMIN.PRZEJAZDY (ID,ODBIOR,CEL) values ('23','tarnów','kraków');
Insert into ADMIN.PRZEJAZDY (ID,ODBIOR,CEL) values ('24','kraków ','kielce');
Insert into ADMIN.PRZEJAZDY (ID,ODBIOR,CEL) values ('25','kielce','krakow');
Insert into ADMIN.PRZEJAZDY (ID,ODBIOR,CEL) values ('26','kraków','kielce');
Insert into ADMIN.PRZEJAZDY (ID,ODBIOR,CEL) values ('27','kraków','kielce');
Insert into ADMIN.PRZEJAZDY (ID,ODBIOR,CEL) values ('28','kraków','kielce');
Insert into ADMIN.PRZEJAZDY (ID,ODBIOR,CEL) values ('29','kraków','kielce');
Insert into ADMIN.PRZEJAZDY (ID,ODBIOR,CEL) values ('46','kraków','kielce');
Insert into ADMIN.PRZEJAZDY (ID,ODBIOR,CEL) values ('48','kraków','kielce');
Insert into ADMIN.PRZEJAZDY (ID,ODBIOR,CEL) values ('49','poznań','tarnów');
Insert into ADMIN.PRZEJAZDY (ID,ODBIOR,CEL) values ('51','kielce orkna','kielce');
Insert into ADMIN.PRZEJAZDY (ID,ODBIOR,CEL) values ('52','kielce','staszów');
Insert into ADMIN.PRZEJAZDY (ID,ODBIOR,CEL) values ('87','staszów','kraków');
Insert into ADMIN.PRZEJAZDY (ID,ODBIOR,CEL) values ('88','warszawa','kraków');
Insert into ADMIN.PRZEJAZDY (ID,ODBIOR,CEL) values ('89','warszawa','kraków');
Insert into ADMIN.PRZEJAZDY (ID,ODBIOR,CEL) values ('90','staszów','kielce');
Insert into ADMIN.PRZEJAZDY (ID,ODBIOR,CEL) values ('91','Kraków','warszawa');
Insert into ADMIN.PRZEJAZDY (ID,ODBIOR,CEL) values ('92','kielce','kraków');
Insert into ADMIN.PRZEJAZDY (ID,ODBIOR,CEL) values ('93','kielce','kraków');
Insert into ADMIN.PRZEJAZDY (ID,ODBIOR,CEL) values ('94','kielce','kraków');
Insert into ADMIN.PRZEJAZDY (ID,ODBIOR,CEL) values ('97','warszawa','kraków');
Insert into ADMIN.PRZEJAZDY (ID,ODBIOR,CEL) values ('98','warszawa','kraków');
Insert into ADMIN.PRZEJAZDY (ID,ODBIOR,CEL) values ('99','kielce','kraków');
Insert into ADMIN.PRZEJAZDY (ID,ODBIOR,CEL) values ('100','kielce','kraków');
Insert into ADMIN.PRZEJAZDY (ID,ODBIOR,CEL) values ('101','staszów','kielce');
Insert into ADMIN.PRZEJAZDY (ID,ODBIOR,CEL) values ('102','staszów','kielce');
Insert into ADMIN.PRZEJAZDY (ID,ODBIOR,CEL) values ('103','staszów','kielce');
Insert into ADMIN.PRZEJAZDY (ID,ODBIOR,CEL) values ('1','SWIETOKRZYSKA 2','WOJEWODZKA 3');
Insert into ADMIN.PRZEJAZDY (ID,ODBIOR,CEL) values ('2','SWIETOKRZYSKA 2','SANDOMIERSKA 5');
Insert into ADMIN.PRZEJAZDY (ID,ODBIOR,CEL) values ('3','ZAGORKSA 13','SANDOMIERSKA 5');
Insert into ADMIN.PRZEJAZDY (ID,ODBIOR,CEL) values ('4','ZAGORKSA 13','BOHATEROW WARSZAWY 2');
Insert into ADMIN.PRZEJAZDY (ID,ODBIOR,CEL) values ('5','STOLARSKA 6','STUDENCKA 2');
Insert into ADMIN.PRZEJAZDY (ID,ODBIOR,CEL) values ('6','MASLOWSKA 3','STUDENCKA 2');
Insert into ADMIN.PRZEJAZDY (ID,ODBIOR,CEL) values ('7','ORKANA 2','WARSZAWKSA 25');
Insert into ADMIN.PRZEJAZDY (ID,ODBIOR,CEL) values ('50','kielce','tarnów');
Insert into ADMIN.PRZEJAZDY (ID,ODBIOR,CEL) values ('41','kielce','kraków');
Insert into ADMIN.PRZEJAZDY (ID,ODBIOR,CEL) values ('42','kielce','kraków');
Insert into ADMIN.PRZEJAZDY (ID,ODBIOR,CEL) values ('43','kielce','kraków');
Insert into ADMIN.PRZEJAZDY (ID,ODBIOR,CEL) values ('44','kraków','kielce');
Insert into ADMIN.PRZEJAZDY (ID,ODBIOR,CEL) values ('45','kraków','kielce');
Insert into ADMIN.PRZEJAZDY (ID,ODBIOR,CEL) values ('47','gdynia','gdańsk');
Insert into ADMIN.PRZEJAZDY (ID,ODBIOR,CEL) values ('53','staszów','połaniec');
Insert into ADMIN.PRZEJAZDY (ID,ODBIOR,CEL) values ('54','staszów','kielce');
Insert into ADMIN.PRZEJAZDY (ID,ODBIOR,CEL) values ('55','staszów','łubnice');
Insert into ADMIN.PRZEJAZDY (ID,ODBIOR,CEL) values ('56','staszów','łubnice');
Insert into ADMIN.PRZEJAZDY (ID,ODBIOR,CEL) values ('57','staszów','kilce');
Insert into ADMIN.PRZEJAZDY (ID,ODBIOR,CEL) values ('58','kielce','staszów');
Insert into ADMIN.PRZEJAZDY (ID,ODBIOR,CEL) values ('59','staszów','kielce');
Insert into ADMIN.PRZEJAZDY (ID,ODBIOR,CEL) values ('60','łubnice','kielce');
Insert into ADMIN.PRZEJAZDY (ID,ODBIOR,CEL) values ('61','łubnice','kielce');
Insert into ADMIN.PRZEJAZDY (ID,ODBIOR,CEL) values ('62','staszów','połaniec');
Insert into ADMIN.PRZEJAZDY (ID,ODBIOR,CEL) values ('63','staszó','kraków');
Insert into ADMIN.PRZEJAZDY (ID,ODBIOR,CEL) values ('64','kielce','staszów');
Insert into ADMIN.PRZEJAZDY (ID,ODBIOR,CEL) values ('65','staszów','kielce');
Insert into ADMIN.PRZEJAZDY (ID,ODBIOR,CEL) values ('66','kielce','staszów');
Insert into ADMIN.PRZEJAZDY (ID,ODBIOR,CEL) values ('81','staszów','kielce');
Insert into ADMIN.PRZEJAZDY (ID,ODBIOR,CEL) values ('82','staszów','staszów 1');
Insert into ADMIN.PRZEJAZDY (ID,ODBIOR,CEL) values ('83','kraków','gdynia');
Insert into ADMIN.PRZEJAZDY (ID,ODBIOR,CEL) values ('84','staszów','kielce');
Insert into ADMIN.PRZEJAZDY (ID,ODBIOR,CEL) values ('85','staszów','kielce');
Insert into ADMIN.PRZEJAZDY (ID,ODBIOR,CEL) values ('86','staszów','staszów 43');
Insert into ADMIN.PRZEJAZDY (ID,ODBIOR,CEL) values ('95','tarnów','tarnobrzego');
Insert into ADMIN.PRZEJAZDY (ID,ODBIOR,CEL) values ('96','tarnów','gdynia');
REM INSERTING into ADMIN.REZERWACJE
SET DEFINE OFF;
Insert into ADMIN.REZERWACJE (ID,ID_KIEROWCY,ID_KLIENTA,CENA,ID_ZAMOWIENIA,ID_PRZEJAZDU,DATA_ROZPOCZECIA,DATA_ZAKONCZENIA,CZAS_ZAKOCZENIA,CZAS_ROZPOCZECIA) values ('21','2','1','134',null,'90',to_date('19/02/06','RR/MM/DD'),to_date('19/02/06','RR/MM/DD'),null,null);
Insert into ADMIN.REZERWACJE (ID,ID_KIEROWCY,ID_KLIENTA,CENA,ID_ZAMOWIENIA,ID_PRZEJAZDU,DATA_ROZPOCZECIA,DATA_ZAKONCZENIA,CZAS_ZAKOCZENIA,CZAS_ROZPOCZECIA) values ('22','1','1','611',null,'91',to_date('19/02/05','RR/MM/DD'),to_date('19/02/05','RR/MM/DD'),null,null);
Insert into ADMIN.REZERWACJE (ID,ID_KIEROWCY,ID_KLIENTA,CENA,ID_ZAMOWIENIA,ID_PRZEJAZDU,DATA_ROZPOCZECIA,DATA_ZAKONCZENIA,CZAS_ZAKOCZENIA,CZAS_ROZPOCZECIA) values ('24','3','1','613',null,'98',to_date('19/02/05','RR/MM/DD'),to_date('19/02/05','RR/MM/DD'),'70/01/01','70/01/01 15:07:43,000000000');
Insert into ADMIN.REZERWACJE (ID,ID_KIEROWCY,ID_KLIENTA,CENA,ID_ZAMOWIENIA,ID_PRZEJAZDU,DATA_ROZPOCZECIA,DATA_ZAKONCZENIA,CZAS_ZAKOCZENIA,CZAS_ROZPOCZECIA) values ('25','2','1','246',null,'99',to_date('19/02/06','RR/MM/DD'),to_date('19/02/06','RR/MM/DD'),'70/01/01','15:15:57');
Insert into ADMIN.REZERWACJE (ID,ID_KIEROWCY,ID_KLIENTA,CENA,ID_ZAMOWIENIA,ID_PRZEJAZDU,DATA_ROZPOCZECIA,DATA_ZAKONCZENIA,CZAS_ZAKOCZENIA,CZAS_ROZPOCZECIA) values ('26','1','1','246',null,'100',to_date('19/02/06','RR/MM/DD'),to_date('19/02/06','RR/MM/DD'),'70/01/01','15:15:57');
Insert into ADMIN.REZERWACJE (ID,ID_KIEROWCY,ID_KLIENTA,CENA,ID_ZAMOWIENIA,ID_PRZEJAZDU,DATA_ROZPOCZECIA,DATA_ZAKONCZENIA,CZAS_ZAKOCZENIA,CZAS_ROZPOCZECIA) values ('27','3','1','134',null,'103',to_date('19/02/06','RR/MM/DD'),to_date('19/02/06','RR/MM/DD'),'16:14:54','15:11:19');
Insert into ADMIN.REZERWACJE (ID,ID_KIEROWCY,ID_KLIENTA,CENA,ID_ZAMOWIENIA,ID_PRZEJAZDU,DATA_ROZPOCZECIA,DATA_ZAKONCZENIA,CZAS_ZAKOCZENIA,CZAS_ROZPOCZECIA) values ('1','1','1','24','1',null,to_date('19/01/03','RR/MM/DD'),to_date('19/01/03','RR/MM/DD'),null,null);
Insert into ADMIN.REZERWACJE (ID,ID_KIEROWCY,ID_KLIENTA,CENA,ID_ZAMOWIENIA,ID_PRZEJAZDU,DATA_ROZPOCZECIA,DATA_ZAKONCZENIA,CZAS_ZAKOCZENIA,CZAS_ROZPOCZECIA) values ('2','1','2','15','1',null,to_date('19/01/03','RR/MM/DD'),to_date('19/01/03','RR/MM/DD'),null,null);
Insert into ADMIN.REZERWACJE (ID,ID_KIEROWCY,ID_KLIENTA,CENA,ID_ZAMOWIENIA,ID_PRZEJAZDU,DATA_ROZPOCZECIA,DATA_ZAKONCZENIA,CZAS_ZAKOCZENIA,CZAS_ROZPOCZECIA) values ('3','2','3','32','2',null,to_date('19/01/03','RR/MM/DD'),to_date('19/01/03','RR/MM/DD'),null,null);
Insert into ADMIN.REZERWACJE (ID,ID_KIEROWCY,ID_KLIENTA,CENA,ID_ZAMOWIENIA,ID_PRZEJAZDU,DATA_ROZPOCZECIA,DATA_ZAKONCZENIA,CZAS_ZAKOCZENIA,CZAS_ROZPOCZECIA) values ('4','3','3','32',null,'1',to_date('19/01/03','RR/MM/DD'),to_date('19/01/03','RR/MM/DD'),null,null);
Insert into ADMIN.REZERWACJE (ID,ID_KIEROWCY,ID_KLIENTA,CENA,ID_ZAMOWIENIA,ID_PRZEJAZDU,DATA_ROZPOCZECIA,DATA_ZAKONCZENIA,CZAS_ZAKOCZENIA,CZAS_ROZPOCZECIA) values ('5','3','4','32',null,'2',to_date('19/01/03','RR/MM/DD'),to_date('19/01/03','RR/MM/DD'),null,null);
Insert into ADMIN.REZERWACJE (ID,ID_KIEROWCY,ID_KLIENTA,CENA,ID_ZAMOWIENIA,ID_PRZEJAZDU,DATA_ROZPOCZECIA,DATA_ZAKONCZENIA,CZAS_ZAKOCZENIA,CZAS_ROZPOCZECIA) values ('10','3','2','32',null,'3',to_date('19/01/03','RR/MM/DD'),to_date('19/01/03','RR/MM/DD'),null,null);
Insert into ADMIN.REZERWACJE (ID,ID_KIEROWCY,ID_KLIENTA,CENA,ID_ZAMOWIENIA,ID_PRZEJAZDU,DATA_ROZPOCZECIA,DATA_ZAKONCZENIA,CZAS_ZAKOCZENIA,CZAS_ROZPOCZECIA) values ('11','2','1','32',null,'4',to_date('19/01/03','RR/MM/DD'),to_date('19/01/03','RR/MM/DD'),null,null);
Insert into ADMIN.REZERWACJE (ID,ID_KIEROWCY,ID_KLIENTA,CENA,ID_ZAMOWIENIA,ID_PRZEJAZDU,DATA_ROZPOCZECIA,DATA_ZAKONCZENIA,CZAS_ZAKOCZENIA,CZAS_ROZPOCZECIA) values ('23','1','1','1386',null,'96',to_date('19/02/06','RR/MM/DD'),to_date('19/02/06','RR/MM/DD'),'70/01/01','70/01/01 15:02:51,000000000');
REM INSERTING into ADMIN.SAMOCHODY
SET DEFINE OFF;
Insert into ADMIN.SAMOCHODY (ID,MARKA,ROK_PRODUKCJI,STAN,MODEL) values ('1','OPEL','2001','SPRAWNY','VECTRA B');
Insert into ADMIN.SAMOCHODY (ID,MARKA,ROK_PRODUKCJI,STAN,MODEL) values ('2','OPEL','2012','SPRAWNY','VECTRA C');
Insert into ADMIN.SAMOCHODY (ID,MARKA,ROK_PRODUKCJI,STAN,MODEL) values ('3','SEAT','2012','SPRAWNY','MONDEO');
Insert into ADMIN.SAMOCHODY (ID,MARKA,ROK_PRODUKCJI,STAN,MODEL) values ('4','FIAT','1842','SPRAWNY','126P');
Insert into ADMIN.SAMOCHODY (ID,MARKA,ROK_PRODUKCJI,STAN,MODEL) values ('5','SEAT','2002','SPRAWNY','IBIZA');
Insert into ADMIN.SAMOCHODY (ID,MARKA,ROK_PRODUKCJI,STAN,MODEL) values ('6','VW','2002','SPRAWNY','PASSAT');
REM INSERTING into ADMIN.ZAMOWIENIA
SET DEFINE OFF;
Insert into ADMIN.ZAMOWIENIA (ID,ODBIOR,CEL) values ('1','WARSZAWSKA 17','ORKANA 44');
Insert into ADMIN.ZAMOWIENIA (ID,ODBIOR,CEL) values ('2','MALIKOW 20','ORKANA 44');
Insert into ADMIN.ZAMOWIENIA (ID,ODBIOR,CEL) values ('3','MALIKOW 20','SKRAJNA 8');
Insert into ADMIN.ZAMOWIENIA (ID,ODBIOR,CEL) values ('4','WESOLA 7','WARSZAWSKA 12');
Insert into ADMIN.ZAMOWIENIA (ID,ODBIOR,CEL) values ('5','DOMASZOWSKA 1','WARSZAWSKA 12');
Insert into ADMIN.ZAMOWIENIA (ID,ODBIOR,CEL) values ('6','DOMASZOWSKA 1','WOJEWODZKA 3');
Insert into ADMIN.ZAMOWIENIA (ID,ODBIOR,CEL) values ('7','ZNIWNA 29','WOJEWODZKA 3');
--------------------------------------------------------
--  DDL for Index KIEROWCY_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "ADMIN"."KIEROWCY_PK" ON "ADMIN"."KIEROWCY" ("ID")
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index KLIENCI_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "ADMIN"."KLIENCI_PK" ON "ADMIN"."KLIENCI" ("ID")
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index OSOBY_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "ADMIN"."OSOBY_PK" ON "ADMIN"."OSOBY" ("ID")
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index PRZEJAZDY_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "ADMIN"."PRZEJAZDY_PK" ON "ADMIN"."PRZEJAZDY" ("ID")
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index REZERWACJE_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "ADMIN"."REZERWACJE_PK" ON "ADMIN"."REZERWACJE" ("ID")
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index SAMOCHODY_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "ADMIN"."SAMOCHODY_PK" ON "ADMIN"."SAMOCHODY" ("ID")
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index ZAMOWIENIA_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "ADMIN"."ZAMOWIENIA_PK" ON "ADMIN"."ZAMOWIENIA" ("ID")
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Trigger KIEROWCY_TRG
--------------------------------------------------------

  CREATE OR REPLACE NONEDITIONABLE TRIGGER "ADMIN"."KIEROWCY_TRG"
BEFORE INSERT ON KIEROWCY
FOR EACH ROW
BEGIN
  <<COLUMN_SEQUENCES>>
  BEGIN
    NULL;
  END COLUMN_SEQUENCES;
END;
/
ALTER TRIGGER "ADMIN"."KIEROWCY_TRG" ENABLE;
--------------------------------------------------------
--  DDL for Trigger KLIENCI_TRG
--------------------------------------------------------

  CREATE OR REPLACE NONEDITIONABLE TRIGGER "ADMIN"."KLIENCI_TRG"
BEFORE INSERT ON KLIENCI
FOR EACH ROW
BEGIN
  <<COLUMN_SEQUENCES>>
  BEGIN
    IF INSERTING AND :NEW.ID IS NULL THEN
      SELECT KLIENCI_SEQ1.NEXTVAL INTO :NEW.ID FROM SYS.DUAL;
    END IF;
  END COLUMN_SEQUENCES;
END;
/
ALTER TRIGGER "ADMIN"."KLIENCI_TRG" ENABLE;
--------------------------------------------------------
--  DDL for Trigger OSOBY_TRG
--------------------------------------------------------

  CREATE OR REPLACE NONEDITIONABLE TRIGGER "ADMIN"."OSOBY_TRG"
BEFORE INSERT ON OSOBY
FOR EACH ROW
BEGIN
  <<COLUMN_SEQUENCES>>
  BEGIN
    IF INSERTING AND :NEW.ID IS NULL THEN
      SELECT OSOBY_SEQ.NEXTVAL INTO :NEW.ID FROM SYS.DUAL;
    END IF;
  END COLUMN_SEQUENCES;
END;
/
ALTER TRIGGER "ADMIN"."OSOBY_TRG" ENABLE;
--------------------------------------------------------
--  DDL for Trigger PRZEJAZDY_TRG
--------------------------------------------------------

  CREATE OR REPLACE NONEDITIONABLE TRIGGER "ADMIN"."PRZEJAZDY_TRG"
BEFORE INSERT ON PRZEJAZDY
FOR EACH ROW
BEGIN
  <<COLUMN_SEQUENCES>>
  BEGIN
    IF INSERTING AND :NEW.ID IS NULL THEN
      SELECT PRZEJAZDY_SEQ.NEXTVAL INTO :NEW.ID FROM SYS.DUAL;
    END IF;
  END COLUMN_SEQUENCES;
END;
/
ALTER TRIGGER "ADMIN"."PRZEJAZDY_TRG" ENABLE;
--------------------------------------------------------
--  DDL for Trigger REZERWACJE_TRG
--------------------------------------------------------

  CREATE OR REPLACE NONEDITIONABLE TRIGGER "ADMIN"."REZERWACJE_TRG"
BEFORE INSERT ON REZERWACJE
FOR EACH ROW
BEGIN
  <<COLUMN_SEQUENCES>>
  BEGIN
    IF INSERTING AND :NEW.ID IS NULL THEN
      SELECT REZERWACJE_SEQ1.NEXTVAL INTO :NEW.ID FROM SYS.DUAL;
    END IF;
  END COLUMN_SEQUENCES;
END;
/
ALTER TRIGGER "ADMIN"."REZERWACJE_TRG" ENABLE;
--------------------------------------------------------
--  DDL for Trigger SAMOCHODY_TRG
--------------------------------------------------------

  CREATE OR REPLACE NONEDITIONABLE TRIGGER "ADMIN"."SAMOCHODY_TRG"
BEFORE INSERT ON SAMOCHODY
FOR EACH ROW
BEGIN
  <<COLUMN_SEQUENCES>>
  BEGIN
    IF INSERTING AND :NEW.ID IS NULL THEN
      SELECT SAMOCHODY_SEQ1.NEXTVAL INTO :NEW.ID FROM SYS.DUAL;
    END IF;
  END COLUMN_SEQUENCES;
END;
/
ALTER TRIGGER "ADMIN"."SAMOCHODY_TRG" ENABLE;
--------------------------------------------------------
--  DDL for Trigger ZAMOWIENIA_TRG
--------------------------------------------------------

  CREATE OR REPLACE NONEDITIONABLE TRIGGER "ADMIN"."ZAMOWIENIA_TRG"
BEFORE INSERT ON ZAMOWIENIA
FOR EACH ROW
BEGIN
  <<COLUMN_SEQUENCES>>
  BEGIN
    IF INSERTING AND :NEW.ID IS NULL THEN
      SELECT ZAMOWIENIA_SEQ.NEXTVAL INTO :NEW.ID FROM SYS.DUAL;
    END IF;
  END COLUMN_SEQUENCES;
END;
/
ALTER TRIGGER "ADMIN"."ZAMOWIENIA_TRG" ENABLE;
--------------------------------------------------------
--  Constraints for Table REZERWACJE
--------------------------------------------------------

  ALTER TABLE "ADMIN"."REZERWACJE" MODIFY ("ID" NOT NULL ENABLE);
  ALTER TABLE "ADMIN"."REZERWACJE" ADD CONSTRAINT "REZERWACJE_PK" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table ZAMOWIENIA
--------------------------------------------------------

  ALTER TABLE "ADMIN"."ZAMOWIENIA" MODIFY ("ID" NOT NULL ENABLE);
  ALTER TABLE "ADMIN"."ZAMOWIENIA" ADD CONSTRAINT "ZAMOWIENIA_PK" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table PRZEJAZDY
--------------------------------------------------------

  ALTER TABLE "ADMIN"."PRZEJAZDY" MODIFY ("ID" NOT NULL ENABLE);
  ALTER TABLE "ADMIN"."PRZEJAZDY" ADD CONSTRAINT "PRZEJAZDY_PK" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table KLIENCI
--------------------------------------------------------

  ALTER TABLE "ADMIN"."KLIENCI" MODIFY ("ID" NOT NULL ENABLE);
  ALTER TABLE "ADMIN"."KLIENCI" ADD CONSTRAINT "KLIENCI_PK" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table KIEROWCY
--------------------------------------------------------

  ALTER TABLE "ADMIN"."KIEROWCY" MODIFY ("ID" NOT NULL ENABLE);
  ALTER TABLE "ADMIN"."KIEROWCY" ADD CONSTRAINT "KIEROWCY_PK" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table SAMOCHODY
--------------------------------------------------------

  ALTER TABLE "ADMIN"."SAMOCHODY" MODIFY ("ID" NOT NULL ENABLE);
  ALTER TABLE "ADMIN"."SAMOCHODY" ADD CONSTRAINT "SAMOCHODY_PK" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "ADMIN"."SAMOCHODY" MODIFY ("MARKA" NOT NULL ENABLE);
  ALTER TABLE "ADMIN"."SAMOCHODY" MODIFY ("ROK_PRODUKCJI" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table OSOBY
--------------------------------------------------------

  ALTER TABLE "ADMIN"."OSOBY" MODIFY ("ID" NOT NULL ENABLE);
  ALTER TABLE "ADMIN"."OSOBY" ADD CONSTRAINT "OSOBY_PK" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "ADMIN"."OSOBY" MODIFY ("IMIE" NOT NULL ENABLE);
  ALTER TABLE "ADMIN"."OSOBY" MODIFY ("NAZWISKO" NOT NULL ENABLE);
--------------------------------------------------------
--  Ref Constraints for Table KIEROWCY
--------------------------------------------------------

  ALTER TABLE "ADMIN"."KIEROWCY" ADD CONSTRAINT "KIE_OSO" FOREIGN KEY ("ID_OSOBY")
	  REFERENCES "ADMIN"."OSOBY" ("ID") ENABLE;
  ALTER TABLE "ADMIN"."KIEROWCY" ADD CONSTRAINT "KIE_SAM" FOREIGN KEY ("ID_SAMOCHODU")
	  REFERENCES "ADMIN"."SAMOCHODY" ("ID") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table KLIENCI
--------------------------------------------------------

  ALTER TABLE "ADMIN"."KLIENCI" ADD CONSTRAINT "KLI_OSO" FOREIGN KEY ("ID_OSOBY")
	  REFERENCES "ADMIN"."OSOBY" ("ID") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table REZERWACJE
--------------------------------------------------------

  ALTER TABLE "ADMIN"."REZERWACJE" ADD CONSTRAINT "REZ_KIE" FOREIGN KEY ("ID_KIEROWCY")
	  REFERENCES "ADMIN"."KIEROWCY" ("ID") ENABLE;
  ALTER TABLE "ADMIN"."REZERWACJE" ADD CONSTRAINT "REZ_KLI" FOREIGN KEY ("ID_KLIENTA")
	  REFERENCES "ADMIN"."KLIENCI" ("ID") ENABLE;
  ALTER TABLE "ADMIN"."REZERWACJE" ADD CONSTRAINT "REZ_PRZE" FOREIGN KEY ("ID_PRZEJAZDU")
	  REFERENCES "ADMIN"."PRZEJAZDY" ("ID") ENABLE;
  ALTER TABLE "ADMIN"."REZERWACJE" ADD CONSTRAINT "REZ_ZAM" FOREIGN KEY ("ID_ZAMOWIENIA")
	  REFERENCES "ADMIN"."ZAMOWIENIA" ("ID") ENABLE;
